#ifndef __FUNC_JACOBIANS_H__
#define __FUNC_JACOBIANS_H__
#include "UtilVnlMatrix.h"

// Jacobian of the normalization operation: n' = n/||n||  ----> dn'/dn
inline void Jac_normalization(vnl_vector_fixed<double, 2> const& n, vnl_vector_fixed<double, 2> &n_o, vnl_matrix_fixed<double, 2, 2> &Jac)
{
	if (n[0] == 0.0 && n[1] == 0.0)
	{
		n_o.fill(0.0);
		Jac.fill(0.0);
		return;
	}
	double const&x = n[0];
	double const&y = n[1];

	double rr = x*x + y*y;
	double r = std::sqrt(rr);
	double f = 1.0 / r;
	double rrr = rr*r;
	double fx = -x / rrr;
	double fy = -y / rrr;

	n_o[0] = x / r;
	n_o[1] = y / r;

	Jac(0, 0) = fx*x + f;
	Jac(0, 1) = fy*x;
	Jac(1, 0) = fx*y;
	Jac(1, 1) = fy*y + f;
}

// Jacobian of the normalization operation: n' = n/||n||  ----> dn'/dn
inline void Jac_normalization(vnl_vector_fixed<double, 3> const& n, vnl_vector_fixed<double, 3> &n_o, vnl_matrix_fixed<double, 3, 3> &Jac)
{
	if (n[0] == 0.0 && n[1] == 0.0 && n[2] == 0.0)
	{
		n_o.fill(0.0);
		Jac.fill(0.0);
		return;
	}

/*	double const&x = n[0];
	double const&y = n[1];
	double const&z = n[2];

	double rr = x*x + y*y + z*z;
	double r = std::sqrt(rr);
	double f = 1.0 / r;
	double rrr = rr*r;
	double fx = -x / rrr;
	double fy = -y / rrr;
	double fz = -z / rrr;

	n_o[0] = x / r;
	n_o[1] = y / r;
	n_o[2] = z / r;

	Jac(0, 0) = fx*x + f;
	Jac(0, 1) = fy*x;
	Jac(0, 2) = fz*x;

	Jac(1, 0) = fx*y;
	Jac(1, 1) = fy*y + f;
	Jac(1, 2) = fz*y;

	Jac(2, 0) = fx*z;
	Jac(2, 1) = fy*z;
	Jac(2, 2) = fz*z + f;
*/
	double const&n0 = n[0];
	double const&n1 = n[1];
	double const&n2 = n[2];

	double t2 = n0*n0;
	double t3 = n1*n1;
	double t4 = n2*n2;
	double t5 = t2 + t3 + t4;
	double t6 = 1.0 / pow(t5, 3.0 / 2.0);
	double t7 = 1.0 / sqrt(t5);
	Jac[0][0] = t7 - t2*t6;
	Jac[0][1] = -n0*n1*t6;
	Jac[0][2] = -n0*n2*t6;
	Jac[1][0] = -n0*n1*t6;
	Jac[1][1] = t7 - t3*t6;
	Jac[1][2] = -n1*n2*t6;
	Jac[2][0] = -n0*n2*t6;
	Jac[2][1] = -n1*n2*t6;
	Jac[2][2] = t7 - t4*t6;

	n_o[0] = n0*t7;
	n_o[1] = n1*t7;
	n_o[2] = n2*t7;
}

//n_t = w * A^(-T) * n
inline void Jac_affine_on_normal(vnl_matrix_fixed<double, 2, 2> const&A, double w, vnl_vector_fixed<double, 2> const& n, vnl_matrix_fixed<double, 2, 4> &Jac)
{
	double const&a00 = A(0, 0);
	double const&a01 = A(0, 1);
	double const&a10 = A(1, 0);
	double const&a11 = A(1, 1);
	double const&n0 = n[0];
	double const&n1 = n[1];

	// code generated by Matlab Symbolic Mathematic Toolbox
	double t2 = a00*a11;
	double t5 = a01*a10;
	double t3 = t2 - t5;
	double t4 = 1.0 / (t3*t3);
	double t6 = 1.0 / t3;
	double t7 = a01*a11*n0*t4;
	double t8 = n0*t6;
	double t9 = a00*a10*n1*t4;
	Jac[0][0] = -(a11*a11)*n0*t4 + a10*a11*n1*t4;
	Jac[0][1] = -(a10*a10)*n1*t4 + a10*a11*n0*t4;
	Jac[0][2] = t7 - n1*t6 - a01*a10*n1*t4;
	Jac[0][3] = t8 + t9 - a00*a11*n0*t4;
	Jac[1][0] = t7 + n1*t6 - a00*a11*n1*t4;
	Jac[1][1] = -t8 + t9 - a01*a10*n0*t4;
	Jac[1][2] = -(a01*a01)*n0*t4 + a00*a01*n1*t4;
	Jac[1][3] = -(a00*a00)*n1*t4 + a00*a01*n0*t4;
	Jac *= w;
}

//n_t = w * A^(-T) * n
inline void Jac_affine_on_normal(vnl_matrix_fixed<double, 3, 3> const&A, double w, vnl_vector_fixed<double, 3> const& n, vnl_matrix_fixed<double, 3, 9> &Jac)
{
	double const&a00 = A(0, 0);
	double const&a01 = A(0, 1);
	double const&a02 = A(0, 2);
	double const&a10 = A(1, 0);
	double const&a11 = A(1, 1);
	double const&a12 = A(1, 2);
	double const&a20 = A(2, 0);
	double const&a21 = A(2, 1);
	double const&a22 = A(2, 2);
	double const&n0 = n[0];
	double const&n1 = n[1];
	double const&n2 = n[2];

	// code generated by Matlab Symbolic Mathematic Toolbox
	double t3 = a11*a22;
	double t4 = a12*a21;
	double t2 = t3 - t4;
	double t5 = a00*a11*a22;
	double t6 = a01*a12*a20;
	double t7 = a02*a10*a21;
	double t10 = a00*a12*a21;
	double t11 = a01*a10*a22;
	double t12 = a02*a11*a20;
	double t8 = -t10 - t11 - t12 + t5 + t6 + t7;
	double t9 = 1.0 / (t8*t8);
	double t13 = a10*a22;
	double t15 = a12*a20;
	double t14 = t13 - t15;
	double t16 = a10*a21;
	double t18 = a11*a20;
	double t17 = t16 - t18;
	double t19 = 1.0 / t8;
	double t20 = a01*a22;
	double t22 = a02*a21;
	double t21 = t20 - t22;
	double t23 = a00*a22;
	double t25 = a02*a20;
	double t24 = t23 - t25;
	double t26 = a00*a21;
	double t28 = a01*a20;
	double t27 = t26 - t28;
	double t29 = a01*a12;
	double t31 = a02*a11;
	double t30 = t29 - t31;
	double t32 = a00*a12;
	double t34 = a02*a10;
	double t33 = t32 - t34;
	double t35 = a00*a11;
	double t37 = a01*a10;
	double t36 = t35 - t37;
	double t38 = a21*n2*t19;
	double t39 = n0*t2*t21*t9;
	double t40 = a22*n0*t19;
	double t41 = n1*t14*t24*t9;
	double t42 = a20*n1*t19;
	double t43 = n2*t17*t27*t9;
	double t44 = a12*n1*t19;
	double t45 = a10*n2*t19;
	double t46 = a11*n0*t19;
	double t47 = a01*n2*t19;
	double t48 = n0*t21*t30*t9;
	double t49 = a02*n0*t19;
	double t50 = n1*t24*t33*t9;
	double t51 = a00*n1*t19;
	double t52 = n2*t27*t36*t9;
	Jac[0][0] = -n0*(t2*t2)*t9 + n1*t14*t2*t9 - n2*t17*t2*t9;
	Jac[0][1] = -n1*(t14*t14)*t9 + n0*t14*t2*t9 + n2*t14*t17*t9;
	Jac[0][2] = -n2*(t17*t17)*t9 - n0*t17*t2*t9 + n1*t14*t17*t9;
	Jac[0][3] = t38 + t39 - a22*n1*t19 - n1*t14*t21*t9 + n2*t17*t21*t9;
	Jac[0][4] = t40 + t41 - a20*n2*t19 - n0*t2*t24*t9 - n2*t17*t24*t9;
	Jac[0][5] = t42 + t43 - a21*n0*t19 + n0*t2*t27*t9 - n1*t14*t27*t9;
	Jac[0][6] = t44 - a11*n2*t19 - n0*t2*t30*t9 + n1*t14*t30*t9 - n2*t17*t30*t9;
	Jac[0][7] = t45 - a12*n0*t19 + n0*t2*t33*t9 - n1*t14*t33*t9 + n2*t17*t33*t9;
	Jac[0][8] = t46 - a10*n1*t19 - n0*t2*t36*t9 + n1*t14*t36*t9 - n2*t17*t36*t9;
	Jac[1][0] = -t38 + t39 + a22*n1*t19 - n1*t2*t24*t9 + n2*t2*t27*t9;
	Jac[1][1] = -t40 + t41 + a20*n2*t19 - n0*t14*t21*t9 - n2*t14*t27*t9;
	Jac[1][2] = -t42 + t43 + a21*n0*t19 + n0*t17*t21*t9 - n1*t17*t24*t9;
	Jac[1][3] = -n0*(t21*t21)*t9 + n1*t21*t24*t9 - n2*t21*t27*t9;
	Jac[1][4] = -n1*(t24*t24)*t9 + n0*t21*t24*t9 + n2*t24*t27*t9;
	Jac[1][5] = -n2*(t27*t27)*t9 - n0*t21*t27*t9 + n1*t24*t27*t9;
	Jac[1][6] = t47 + t48 - a02*n1*t19 - n1*t24*t30*t9 + n2*t27*t30*t9;
	Jac[1][7] = t49 + t50 - a00*n2*t19 - n0*t21*t33*t9 - n2*t27*t33*t9;
	Jac[1][8] = t51 + t52 - a01*n0*t19 + n0*t21*t36*t9 - n1*t24*t36*t9;
	Jac[2][0] = -t44 + a11*n2*t19 - n0*t2*t30*t9 + n1*t2*t33*t9 - n2*t2*t36*t9;
	Jac[2][1] = -t45 + a12*n0*t19 + n0*t14*t30*t9 - n1*t14*t33*t9 + n2*t14*t36*t9;
	Jac[2][2] = -t46 + a10*n1*t19 - n0*t17*t30*t9 + n1*t17*t33*t9 - n2*t17*t36*t9;
	Jac[2][3] = -t47 + t48 + a02*n1*t19 - n1*t21*t33*t9 + n2*t21*t36*t9;
	Jac[2][4] = -t49 + t50 + a00*n2*t19 - n0*t24*t30*t9 - n2*t24*t36*t9;
	Jac[2][5] = -t51 + t52 + a01*n0*t19 + n0*t27*t30*t9 - n1*t27*t33*t9;
	Jac[2][6] = -n0*(t30*t30)*t9 + n1*t30*t33*t9 - n2*t30*t36*t9;
	Jac[2][7] = -n1*(t33*t33)*t9 + n0*t30*t33*t9 + n2*t33*t36*t9;
	Jac[2][8] = -n2*(t36*t36)*t9 - n0*t30*t36*t9 + n1*t33*t36*t9;
	Jac *= w;
}



#endif