#pragma once

#include <opencv2\opencv.hpp>
#include <UtilMatrix.h>
#include "utility.h"
#include "basic_geometry.h"
#include <UtilVnlMatrix.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vil/vil_convert.h>
#include "CIsoSurface.h"
#include "VilToOpenCv.h"
#include "normal_estimation.h"
#include "color_map.h"
#include "utility.h"
#include "surface_misc.h"
#include "CameraView.h"
#include "DirectXMath.h"
#include "CustomSVD.h"
#include <omp.h>
#include "CConnectedComponent.h"
#include "MorphologicalOperation.h"
#include "normal_estimation.h"
#include "zlib_compression.h"
#include "VecOperation.h"
#include "iniFileParser.h"
#include <vgl/vgl_point_3d.h>
#include <vgl/vgl_point_2d.h>
#include <vgl/vgl_line_3d_2_points.h>
#include <vgl/vgl_infinite_line_3d.h>
#include <vgl/vgl_intersection.h>
#include <vgl/vgl_line_segment_2d.h>
#include <vgl/vgl_line_2d.h>
